import images from "./image";
const data = [
  {
    id: 1,
    title: "아메리카노",
    price: 2500,
    img: images.americano,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 2,
    title: "카페라떼",
    price: 3000,
    img: images.latte,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 3,
    title: "바닐라라떼",
    price: 3500,
    img: images.vanillaLatte,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 4,
    title: "돌체라떼",
    price: 4000,
    img: images.dolceLatte,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 5,
    title: "코코넛라떼",
    price: 4000,
    img: images.coconutLatte,
    category: "커피",
    icecreamTopping: 0,
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 6,
    title: "카푸치노",
    price: 3000,
    img: images.cappuccino,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 7,
    title: "카라멜마키아또",
    price: 3500,
    img: images.caramel,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 8,
    title: "플랫화이트",
    price: 3000,
    img: images.flatWhite,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 9,
    title: "구아바모히또",
    price: 3500,
    img: images.mojito,
    category: "에이드",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 10,
    title: "레몬에이드",
    price: 3000,
    img: images.lemon,
    category: "에이드",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 11,
    title: "자몽에이드",
    price: 3000,
    img: images.grapefruit,
    category: "에이드",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 12,
    title: "청포도에이드",
    price: 3000,
    img: images.greengrape,
    category: "에이드",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 13,
    title: "체리에이드",
    price: 3000,
    img: images.cherry,
    category: "에이드",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 14,
    title: "키위에이드",
    price: 3000,
    img: images.kiwi,
    category: "에이드",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 15,
    title: "패션코코에이드",
    price: 3500,
    img: images.passioncoco,
    category: "에이드",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 16,
    title: "리치티에이드",
    price: 3000,
    img: images.lycheetea,
    category: "에이드",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 17,
    title: "플레인요거트스무디",
    price: 3500,
    img: images.plainSm,
    category: "스무디",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 18,
    title: "딸기스무디",
    price: 3500,
    img: images.strawberrySm,
    category: "스무디",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 19,
    title: "망고스무디",
    price: 3500,
    img: images.mangoSm,
    category: "스무디",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 20,
    title: "망고바나나스무디",
    price: 4000,
    img: images.mangobananaSm,
    category: "스무디",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 21,
    title: "블루베리스무디",
    price: 4000,
    img: images.blueberrySm,
    category: "스무디",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 22,
    title: "자몽스무디",
    price: 4000,
    img: images.grapefruitSm,
    category: "스무디",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["iced"],
  },
  {
    id: 23,
    title: "고구마라떼",
    price: 3000,
    img: images.sweetpotatoLa,
    category: "라떼&음료",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 24,
    title: "녹차라떼",
    price: 3000,
    img: images.greenteaLa,
    category: "라떼&음료",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 25,
    title: "단호박라떼",
    price: 3000,
    img: images.pumpkinLa,
    category: "라떼&음료",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 26,
    title: "오곡라떼",
    price: 3000,
    img: images.fivegrainLa,
    category: "라떼&음료",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 27,
    title: "아이스초코",
    price: 3000,
    img: images.icedchocolateLa,
    category: "라떼&음료",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
  },
  {
    id: 28,
    title: "딸기티",
    price: 3000,
    img: images.strawberryTea,
    category: "티",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot"],
  },
  {
    id: 29,
    title: "레몬티",
    price: 3000,
    img: images.lemonTea,
    category: "티",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot"],
  },
  {
    id: 30,
    title: "밀크티",
    price: 3500,
    img: images.milkTea,
    category: "티",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot"],
  },
  {
    id: 31,
    title: "애플시나몬티",
    price: 3500,
    img: images.applecinnamonTea,
    category: "티",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot"],
  },
  {
    id: 32,
    title: "얼그레이",
    price: 3000,
    img: images.earlgreyTea,
    category: "티",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot"],
  },
  {
    id: 33,
    title: "유스베리티",
    price: 3500,
    img: images.blueberryTea,
    category: "티",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot"],
  },
  {
    id: 34,
    title: "유자피나콜라다티",
    price: 3500,
    img: images.yuzupinacoladaTea,
    category: "티",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot"],
  },
  {
    id: 35,
    title: "캐모마일티",
    price: 3000,
    img: images.chamomileTea,
    category: "티",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot"],
  },
  {
    id: 36,
    title: "허니자몽블랙티",
    price: 3500,
    img: images.joneyjasmineblackTea,
    category: "티",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot"],
  },
];
export default data;
